import * as THREE from 'three';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.165.0/examples/jsm/controls/OrbitControls.js';
import { sampleGcode } from './engine.js';
import { binaryStl as encodeBinaryStl, asciiStl } from './exporter.js';

const $ = selector => document.querySelector(selector);
const state = { source: '', filename: 'model', result: null, worker: null, orthographic: false, wireframe: false };
const scene = new THREE.Scene(); scene.background = new THREE.Color('#0b171c');
const perspective = new THREE.PerspectiveCamera(42, 1, .1, 2000), orthographic = new THREE.OrthographicCamera(-100,100,100,-100,.1,2000);
let camera = perspective, mesh = null;
const renderer = new THREE.WebGLRenderer({ antialias: true, preserveDrawingBuffer: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); $('#viewer').append(renderer.domElement);
const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true;
scene.add(new THREE.HemisphereLight('#e8f0f2','#071014', 2.1)); const light = new THREE.DirectionalLight('#fff', 2); light.position.set(60,80,90); scene.add(light);
const grid = new THREE.GridHelper(220, 22, '#42585e', '#1a2c31'); scene.add(grid);
function resize(){const box=$('#viewer').getBoundingClientRect(); renderer.setSize(box.width,box.height); camera.aspect=box.width/box.height; if(camera.isPerspectiveCamera) camera.updateProjectionMatrix(); else {const s=Math.max(box.width,box.height)/5; camera.left=-s;camera.right=s;camera.top=s;camera.bottom=-s;camera.updateProjectionMatrix()} renderer.render(scene,camera)}
new ResizeObserver(resize).observe($('#viewer')); function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)} animate();
function formSettings(){const data=new FormData($('#settings')); return {width:Number(data.get('width')),height:Number(data.get('height')),arcResolution:Number(data.get('arcResolution')),includeInfill:data.has('includeInfill'),ignoreSkirt:data.has('ignoreSkirt'),ignoreBrim:data.has('ignoreSkirt'),ignoreSupports:data.has('ignoreSupports')};}
function clearMesh(){if(mesh){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();mesh=null}}
function selectedLayers(){if(!state.result)return[];const index=Number($('#layer').value), mode=$('#layer-mode').value; return mode==='one'?[state.result.meshLayers[index]]:mode==='through'?state.result.meshLayers.slice(0,index+1):state.result.meshLayers;}
function refreshMesh(){const layers=selectedLayers().filter(Boolean);clearMesh();if(!layers.length)return;let size=layers.reduce((n,l)=>n+l.vertices.length,0), positions=new Float32Array(size),offset=0;layers.forEach(layer=>{positions.set(layer.vertices,offset);offset+=layer.vertices.length});const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.computeVertexNormals();mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:$('#model-color').value,roughness:.58,metalness:.08,wireframe:state.wireframe,side:THREE.DoubleSide}));/* G-code is XY build plane with Z up; Three.js uses XZ as its build plane and Y as up. */mesh.rotation.x=-Math.PI/2;scene.add(mesh);mesh.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(mesh), center=bounds.getCenter(new THREE.Vector3());/* Recentre arbitrary slicer coordinates and put the first bead on the plate. */mesh.position.set(-center.x,-bounds.min.y,-center.z);mesh.updateMatrixWorld(true);fitCamera();}
function fitCamera(){if(!mesh)return;const box=new THREE.Box3().setFromObject(mesh), center=box.getCenter(new THREE.Vector3()), size=box.getSize(new THREE.Vector3()).length()||50; controls.target.copy(center); camera.position.copy(center).add(new THREE.Vector3(size*.72,size*.9,size*.9));camera.near=Math.max(.01,size/100);camera.far=size*20;camera.updateProjectionMatrix();controls.update()}
function stats(){const s=state.result.stats, density=Number(new FormData($('#settings')).get('density')), diameter=Number(new FormData($('#settings')).get('filamentDiameter'));const radius=diameter/2, grams=s.filamentMm*Math.PI*radius*radius/1000*density;const dims=['x','y','z'].map(k=>(s.max[k]-s.min[k]).toFixed(1)).join(' × ');const rows=[['File',state.filename],['Layers',s.layers],['Dimensions',`${dims} mm`],['Bounds',`${s.min.x.toFixed(1)}, ${s.min.y.toFixed(1)}, ${s.min.z.toFixed(1)} → ${s.max.x.toFixed(1)}, ${s.max.y.toFixed(1)}, ${s.max.z.toFixed(1)}`],['Slicer',s.slicer],['Nozzle',s.nozzle?`${s.nozzle} mm`:'Not found'],['Layer height',s.layerHeight?`${s.layerHeight} mm`:'Detected from paths'],['Filament',`${(s.filamentMm/1000).toFixed(2)} m / ${grams.toFixed(1)} g`],['Print speed',`${s.speedMin.toFixed(0)}–${s.speedMax.toFixed(0)} mm/s`],['Extrusion / travel',`${s.extrusionDistance.toFixed(0)} / ${s.travelDistance.toFixed(0)} mm`],['Retractions',s.retractions],['Tool changes',s.toolChanges],['Commands',s.commands]];$('#stats').innerHTML=rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');$('#warnings').innerHTML=s.warnings.length?s.warnings.map(w=>`<li>${w}</li>`).join(''):'<li>No unsupported commands observed.</li>';}
function setReady(){const count=state.result.meshLayers.length;$('#layer').max=Math.max(0,count-1);$('#layer').value=Math.max(0,count-1);$('#layer').disabled=!count;$('#layer-label').textContent=count?`Layer ${count} of ${count}`:'No layers';['#export-binary','#export-ascii','#export-json'].forEach(x=>$(x).disabled=!count);$('#viewer-state').textContent=`${count} layers rebuilt`;refreshMesh();stats();}
function rebuild(){if(!state.source)return; if(state.source.length>100*1024*1024){$('#file-note').textContent='This file exceeds the 100 MB local-memory safety limit.';return}if(state.worker)state.worker.terminate();$('#viewer-state').textContent='Rebuilding locally…';$('#progress').style.width='0%';state.worker=new Worker('./worker.js',{type:'module'});state.worker.onmessage=({data})=>{if(data.type==='progress')$('#progress').style.width=`${data.progress}%`;if(data.type==='error'){$('#file-note').textContent=`Could not rebuild: ${data.message}`;$('#viewer-state').textContent='Conversion failed'}if(data.type==='complete'){state.result=data.result;$('#progress').style.width='100%';setReady();}};state.worker.postMessage({text:state.source,settings:formSettings()});}
function load(text,name){state.source=text;state.filename=name.replace(/\.[^.]+$/,'');$('#file-note').textContent=`${name} · ${(new Blob([text]).size/1024).toFixed(1)} KB · processed locally`;rebuild()}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function vertices(){return selectedLayers().flatMap(layer=>Array.from(layer.vertices));}
$('#file').addEventListener('change',event=>{const file=event.target.files[0];if(file)file.text().then(text=>load(text,file.name))});['dragenter','dragover'].forEach(event=>$('#drop-zone').addEventListener(event,e=>{e.preventDefault();$('#drop-zone').classList.add('drag')}));['dragleave','drop'].forEach(event=>$('#drop-zone').addEventListener(event,e=>{e.preventDefault();$('#drop-zone').classList.remove('drag')}));$('#drop-zone').addEventListener('drop',event=>{const file=event.dataTransfer.files[0];if(file)file.text().then(text=>load(text,file.name))});$('#sample').onclick=()=>load(sampleGcode(),'sample-cube.gcode');$('#settings').addEventListener('submit',event=>{event.preventDefault();rebuild()});$('#layer').oninput=()=>{$('#layer-label').textContent=`Layer ${Number($('#layer').value)+1} of ${state.result.meshLayers.length}`;refreshMesh()};$('#layer-mode').onchange=refreshMesh;$('#model-color').oninput=()=>{if(mesh)mesh.material.color.set($('#model-color').value)};$('#background').onchange=()=>scene.background.set($('#background').value);$('#wireframe').onclick=()=>{state.wireframe=!state.wireframe;$('#wireframe').setAttribute('aria-pressed',state.wireframe);if(mesh)mesh.material.wireframe=state.wireframe};$('#orthographic').onclick=()=>{state.orthographic=!state.orthographic;const old=camera;camera=state.orthographic?orthographic:perspective;camera.position.copy(old.position);controls.object=camera;$('#orthographic').setAttribute('aria-pressed',state.orthographic);fitCamera();resize()};$('#reset-camera').onclick=fitCamera;$('#fullscreen').onclick=()=>$('#viewer').requestFullscreen?.();$('#export-binary').onclick=()=>download(`${state.filename}-rebuilt.stl`,new Blob([encodeBinaryStl(vertices())],{type:'model/stl'}));$('#export-ascii').onclick=()=>download(`${state.filename}-rebuilt-ascii.stl`,new Blob([asciiStl(state.filename,vertices())],{type:'model/stl'}));$('#export-json').onclick=()=>download(`${state.filename}-report.json`,new Blob([JSON.stringify(state.result.stats,null,2)],{type:'application/json'}));
