import assert from 'node:assert/strict';
import { reconstructGcode, sampleGcode } from '../engine.js';
import { readFile } from 'node:fs/promises';
import { binaryStl, asciiStl } from '../exporter.js';
const rebuild = source => reconstructGcode(source, { width:.45, height:.2, includeInfill:true, ignoreSkirt:false, ignoreBrim:false, ignoreSupports:false });
let result = rebuild(sampleGcode()); assert.equal(result.stats.layers, 2); assert.ok(result.meshLayers.every(layer => layer.vertices.length > 0));
result = rebuild('G90\nM82\nG1 X0 Y0 Z.2\nG1 X10 E1\nG92 E0\nG1 X20 E1\n'); assert.equal(result.stats.extrusionDistance, 20);
result = rebuild('G91\nM83\nG1 Z.2\nG1 X5 E.3\nG1 X5 E-.8\nG1 X5 E.3\n'); assert.equal(result.stats.retractions, 1); assert.ok(result.stats.travelDistance >= 5);
result = rebuild('G90\nG1 Z.2\nG1 X0 Y0\nG1 X10 E1\nT1\nG1 X20 E1\nG2 X30 Y10 I0 J10 E2\n'); assert.equal(result.stats.toolChanges, 1); assert.ok(result.meshLayers[0].vertices.length > 36);
result = rebuild(';TYPE:SUPPORT\nG90\nG1 Z.2\nG1 X-10 Y-10\nG1 X10 E1\n'); assert.equal(result.stats.layers, 1); assert.ok(result.stats.min.x < 0);
result = rebuild('G28\nM900 K.05\nG1 X0 Y0 Z.2\nG1 X10 E1\n'); assert.ok(result.stats.warnings.some(item => item.startsWith('G28')));
const curaPurge = `;FLAVOR:Marlin\nG90\nM82\nG92 E0\nG1 X5 Y5 Z.2\nG1 X5 Y180 E12\nG92 E0\n;LAYER:0\n;TYPE:WALL-OUTER\nG1 X50 Y50\nG1 X70 Y50 E1\nG1 X70 Y70 E2\nG1 X50 Y70 E3\nG1 X50 Y50 E4\n`;
result = rebuild(curaPurge); assert.equal(result.stats.startupPurgeSegments, 1); assert.equal(result.stats.startupPurgeExcluded, 1); assert.equal(result.stats.min.x, 50);
result = reconstructGcode(curaPurge, { ignoreStartupPurge:false, ignoreSkirt:false, ignoreBrim:false, ignoreSupports:false }); assert.equal(result.stats.startupPurgeExcluded, 0); assert.equal(result.stats.min.x, 5);
const prusaPurge = `G90\nM83\nG92 E0\nG1 X3 Y10 Z.2\nG1 X3 Y190 E8\n;LAYER_CHANGE\n;Z:0.2\n;TYPE:External perimeter\nG1 X40 Y40\nG1 X60 Y40 E.8\nG1 X60 Y60 E.8\nG1 X40 Y60 E.8\n`;
result = rebuild(prusaPurge); assert.equal(result.stats.startupPurgeExcluded, 1); assert.equal(result.stats.min.x, 40);
const noCommentModel = `G90\nM82\nG92 E0\nG1 X5 Y5 Z.2\nG1 X55 Y5 E1\nG1 X55 Y55 E2\nG1 X5 Y55 E3\nG1 X5 Y5 E4\n`;
result = rebuild(noCommentModel); assert.equal(result.stats.startupPurgeExcluded, 0); assert.equal(result.stats.min.x, 5);
const crealityPurge = await readFile(new URL('./fixtures/creality-startup-purge.gcode', import.meta.url), 'utf8');
const filteredCreality = rebuild(crealityPurge), includedCreality = reconstructGcode(crealityPurge, { ignoreStartupPurge:false, ignoreSkirt:false, ignoreBrim:false, ignoreSupports:false });
assert.equal(filteredCreality.stats.slicer, 'Creality_Print V7.2.2.5483');
assert.equal(filteredCreality.stats.startupPurgeSegments, 2);
assert.equal(filteredCreality.stats.startupPurgeExcluded, 2);
assert.deepEqual(filteredCreality.stats.startupPurge.segments.map(segment => segment.line), [7, 9]);
assert.ok(filteredCreality.stats.startupPurge.segments.every(segment => segment.classification === 'startup-purge' && segment.startup));
assert.equal(filteredCreality.stats.startupPurge.firstModelExtrusionLine, 25);
assert.equal(filteredCreality.stats.min.x, 118.416);
assert.equal(includedCreality.stats.startupPurgeExcluded, 0);
assert.equal(includedCreality.stats.min.x, -2.4);
const allVertices = result => result.meshLayers.flatMap(layer => Array.from(layer.vertices));
const filteredVertices = allVertices(filteredCreality), includedVertices = allVertices(includedCreality);
assert.ok(includedVertices.length > filteredVertices.length);
assert.equal(binaryStl(filteredVertices).byteLength < binaryStl(includedVertices).byteLength, true);
assert.equal(asciiStl('filtered', filteredVertices).includes('-2.625'), false);
assert.equal(asciiStl('included', includedVertices).includes('-2.625'), true);
const filteredBinary = new DataView(binaryStl(filteredVertices));
for (let offset = 84; offset < filteredBinary.byteLength; offset += 50) for (let coordinate = 0; coordinate < 12; coordinate++) assert.ok(filteredBinary.getFloat32(offset + coordinate * 4, true) > -2, 'filtered binary STL must not contain purge coordinates');
assert.equal(filteredCreality.meshLayers.flatMap(layer => layer.paths).some(path => path.source.classification === 'startup-purge'), false);
assert.equal(includedCreality.meshLayers.flatMap(layer => layer.paths).filter(path => path.source.classification === 'startup-purge').length, 2);
console.log('engine tests passed');
const bytes = binaryStl(Array.from(rebuild(sampleGcode()).meshLayers[0].vertices)); const view = new DataView(bytes); assert.equal(view.byteLength, 84 + view.getUint32(80, true) * 50); assert.ok(view.getUint32(80, true) > 0); console.log('binary STL test passed');
